name: portfolio
version: 1.0.0+1
publish_to: firebase.com
description: Hello there, this is Asfaque. This is my portfolio with my work experience and skills. This site is made with flutter, a cross platform application development framework.
environment: 
  sdk: '>=3.0.6 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  get_storage:
  google_fonts: any
  font_awesome_flutter: any
  url_launcher:
  code_text_field:
  flutter_highlight:
  share_plus: any
  url_strategy: any
  universal_html: any
  responsive_builder: any
  flutter:
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/
    - assets/apps/

