name: portfolio
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.6 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  get_storage:
  google_fonts: any
  font_awesome_flutter: any
  url_launcher:
  code_text_field:
  flutter_highlight:
  share_plus: any
  url_strategy: any
  universal_html: any
  flutter:
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

